services:
  # Frontend Service (Next.js)
  frontend:
    image: frontend-service
    build:
      context: ./website-frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-service
    ports:
      - "3000:3000"
    volumes:
      - ./website-frontend:/app:cached
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
