name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # Step 4: Build and push Docker image to Docker Hub with correct name
      - name: Build and push Docker image
        run: |
          docker build -t hyperx7777/ahtt:latest -f ./frontend-service/Dockerfile ./frontend-service
          docker push hyperx7777/ahtt:latest

      # Step 5: Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Deploy to Azure Container Apps using the Docker image
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp create \
            --name ahttcontainerapp \
            --resource-group ahttresourcegroup \
            --environment ahttcontainerappenv \
            --image hyperx7777/ahtt:latest \
            --target-port 3000 \
            --ingress 'external' \
            --env-vars 'APP_SETTING=my-setting'
